export const LEGAL_ARTICLES = [
  {
    id: 'prop-1',
    category: 'PROPERTY',
    title: 'Property Registration Process',
    content: 'Property registration in West Bengal is a multi-step process governed by the Registration Act, 1908. It involves: (1) Drafting of the Sale Deed by a legal expert. (2) Verification of land records (Porcha/ROR). (3) Payment of stamp duty and registration fees.',
  },
  {
    id: 'prop-2',
    category: 'PROPERTY',
    title: 'Flat Registration Requirements',
    content: 'To register a flat in Kolkata, you must provide: (1) The original Sale Agreement and Sale Deed. (2) Completion Certificate (CC) or Occupancy Certificate. (3) Possession Letter. (4) Property Tax receipts. (5) PAN and Aadhaar copies.',
  },
  {
    id: 'prop-3',
    category: 'PROPERTY',
    title: 'Land Registration in WB',
    content: 'Before registering land in West Bengal, ensure: (1) The seller has a clear Title. (2) Mutation is completed in the seller\'s name. (3) Check the \'Porcha\' (Land Record) in the BL&LRO office. (4) Verify if the land is \'Bastu\' (residential) or agricultural.',
  },
  {
    id: 'cons-1',
    category: 'CONSUMER',
    title: 'Filing Consumer Complaint',
    content: 'If you face a deficiency in service or unfair trade practice, you can file a complaint under the Consumer Protection Act, 2019. (1) Send a formal notice to the opposite party giving 15 days to resolve. (2) If no resolution, file a complaint.',
  },
  {
    id: 'cons-2',
    category: 'CONSUMER',
    title: 'Consumer Protection Act 2019',
    content: 'The new 2019 Act replaced the old 1986 Act, introducing: (1) E-filing of complaints. (2) Conduct of hearings via video conferencing. (3) Inclusion of e-commerce transactions. (4) Product Liability, holding manufacturers accountable.',
  },
  {
    id: 'cons-3',
    category: 'CONSUMER',
    title: 'Product Liability Claim',
    content: 'A manufacturer or service provider is liable for any harm caused by a defective product or deficient service. Compensation can be claimed for injury, property damage, or mental agony caused by the defect.',
  },
  {
    id: 'ten-1',
    category: 'TENANCY',
    title: 'Tenancy Rights (WB)',
    content: 'The West Bengal Premises Tenancy Act governs eviction, fair rent, and common amenities for tenants. A landlord cannot arbitrarily evict a tenant or cut off essential services like water or electricity without a court order.',
  },
  {
    id: 'ten-2',
    category: 'TENANCY',
    title: 'Tenant Eviction Grounds',
    content: 'Grounds include non-payment of rent, sub-letting without consent, or owner\'s personal requirement. The landlord must serve a one-month written notice before filing an eviction suit in the appropriate court.',
  },
  {
    id: 'ten-3',
    category: 'TENANCY',
    title: 'Rent Receipt Importance',
    content: 'Every tenant is entitled to a signed receipt for rent paid. Failure to provide is an offense. If the landlord refuses to issue a receipt, the tenant can remit the rent via postal money order directly.',
  },
  {
    id: 'mat-1',
    category: 'MATRIMONIAL',
    title: 'Mutual Consent Divorce',
    content: 'Under Section 13B of HMA, requires both parties to live separately for 1 year and a 6-month cooling period. Provides an amicable and faster way to dissolve a marriage without contesting allegations.',
  },
  {
    id: 'mat-2',
    category: 'MATRIMONIAL',
    title: 'Contested Divorce Grounds',
    content: 'Cruelty, desertion, adultery, conversion, or mental disorder are valid grounds for contested divorce. Proof is required to establish the claims made in the petition, making it a lengthier process.',
  },
  {
    id: 'mat-3',
    category: 'MATRIMONIAL',
    title: 'Alimony and Maintenance',
    content: 'Section 144 BNSS (formerly 125 CrPC) provides for maintenance to wife, children, and parents to prevent vagrancy. Hindu Adoptions and Maintenance Act also covers maintenance rights of dependants.',
  },
  {
    id: 'mat-4',
    category: 'MATRIMONIAL',
    title: 'Interim Maintenance',
    content: 'Courts can award maintenance during the pendency of the case to meet immediate expenses. It ensures the dependent spouse can sustain themselves and bear required legal expenses.',
  },
  {
    id: 'suc-1',
    category: 'SUCCESSION',
    title: 'Probate of Will',
    content: 'Probate is a court-certified copy of a will. Mandatory in Kolkata/WB for property transfer under Indian Succession Act. It establishes the legal validity and authenticity of the executed will.',
  },
  {
    id: 'suc-2',
    category: 'SUCCESSION',
    title: 'Drafting a Valid Will',
    content: 'Must be in writing, signed by the testator, and attested by at least two witnesses. Registration is not mandatory but highly recommended to prevent future disputes over authenticity.',
  },
  {
    id: 'suc-3',
    category: 'SUCCESSION',
    title: 'Letters of Administration',
    content: 'Required when a person dies intestate (without a will) to manage and distribute the estate. An appointed administrator handles the assets according to applicable succession laws.',
  },
  {
    id: 'civ-1',
    category: 'CIVIL',
    title: 'Partition Suit',
    content: 'Filed to divide joint property among legal heirs. Requires proof of ownership and relationship. Often initiated when co-owners cannot agree on property division or sale proportions.',
  },
  {
    id: 'civ-2',
    category: 'CIVIL',
    title: 'Injunction Suit (Stay Order)',
    content: 'Temporary or permanent order to prevent an action, like illegal construction or eviction. Grants immediate relief to preserve the status quo until the final judgment is conclusively passed.',
  },
  {
    id: 'civ-3',
    category: 'CIVIL',
    title: 'Civil Dispute Resolution',
    content: 'Civil suits can range from recovery of money to specific performance of contracts. Alternative Dispute Resolution (ADR) like mediation or arbitration is encouraged for faster settlement.',
  },
  {
    id: 'crim-1',
    category: 'CRIMINAL',
    title: 'Regular Bail Matter',
    content: 'Applied for when the accused is in custody. Court considers the nature of the crime and flight risk. Ensure strong sureties to secure bail for non-bailable offenses under relevant sections.',
  },
  {
    id: 'crim-2',
    category: 'CRIMINAL',
    title: 'Anticipatory Bail',
    content: 'Section 482 BNSS (formerly 438 CrPC) allows a person to seek bail in anticipation of arrest for non-bailable offenses, often used to prevent targeted harassment in false or fabricated cases.',
  },
  {
    id: 'crim-3',
    category: 'CRIMINAL',
    title: 'Filing an FIR',
    content: 'First Information Report should be filed at the nearest police station for cognizable offenses. If police refuse, a complaint can be filed before a Magistrate under Section 175 BNSS.',
  }
];
